TE5-T69 Swift-Basics
jay-a-shah/ios_Demo-app1 pull request #1
Opened 2022-01-17 13:52 UTC by jay-a-shah

2022-01-19 03:51 UTC, purvesh-d commented on Demo app/Demo app/AppDelegate.swift
> +
Remove extra empty lines

2022-01-19 03:53 UTC, purvesh-d requested changes

2022-01-19 03:53 UTC, purvesh-d commented on Demo app/Demo app/SceneDelegate.swift
> +
Remove extra empty lines

2022-01-19 03:53 UTC, purvesh-d commented on Demo app/Demo app/ViewController.swift
> +
Remove extra empty lines

2022-01-19 03:53 UTC, purvesh-d commented on Temporary.playground/Contents.swift
> +}
Why this playground name is temporary? can't we give some meaningful name?

2022-01-19 03:54 UTC, purvesh-d commented
- Remove extra empty lines from all the files.
-  Make single commits only.

2022-01-19 14:31 UTC, jay-a-shah commented on Demo app/Demo app/AppDelegate.swift
> +
resolved

2022-01-19 14:32 UTC, jay-a-shah commented on Demo app/Demo app/SceneDelegate.swift
> +
okk I will Resolve It

2022-01-21 12:24 UTC, purvesh-d requested changes

2022-01-21 12:24 UTC, purvesh-d commented on Swift- Exercise.playground/Contents.swift
> +
extra empty line

2022-01-21 12:24 UTC, purvesh-d commented on Swift- Exercise.playground/Contents.swift
> +for i in listOfNumbers{
Code formating required

2022-01-21 12:24 UTC, purvesh-d commented on Swift-Basics .playground/Contents.swift
> +print(customersInLine.count)
Extra spaces

2022-01-21 12:42 UTC, merged