TE5-T312 Swift Advance Topics (First 5)
jay-a-shah/ios_Demo-app1 pull request #2
Opened 2022-01-24 13:30 UTC by jay-a-shah

2022-01-27 04:15 UTC, purvesh-d requested changes
- Make single commit
- Code formatting

2022-02-04 05:44 UTC, purvesh-d requested changes

2022-02-04 05:44 UTC, purvesh-d commented on Demo app/Demo app/SecondViewController.swift
> +class SecondViewController: UIViewController {
put empty line before starting class

2022-02-04 05:44 UTC, purvesh-d commented on Demo app/Demo app/ViewController.swift
> +    @IBOutlet weak var textLabel: UILabel!
Put `//MARK:- Outlets`

2022-02-04 05:44 UTC, purvesh-d commented on Demo app/Demo app/ViewController.swift
> +    @IBAction func goToSecondView(_ sender: UIButton) {
Create extension for action and put all action func inside it.

2022-02-04 05:44 UTC, purvesh-d commented on Swift-Advance-Exercise.playground/Contents.swift
> +class Two{
`class Two {`

2022-02-04 05:44 UTC, purvesh-d commented on Swift-Advance-Exercise.playground/Contents.swift
> +        for i in input{
`for i in input {`

2022-02-04 11:24 UTC, purvesh-d requested changes

2022-02-04 11:24 UTC, purvesh-d commented on Demo app/Demo app/SecondViewController.swift
> +//MARK: - Outlet
Proper indentation

2022-02-04 11:24 UTC, purvesh-d commented on Demo app/Demo app/ViewController.swift
> +    @IBOutlet weak var textLabel: UILabel!
Proper indentation

2022-02-04 11:24 UTC, purvesh-d commented on Swift-Advance.playground/Contents.swift
> +
Empty extra lines

2022-02-04 11:24 UTC, purvesh-d commented on Swift-Advance.playground/Contents.swift
> +enum Laptop{
Space requierd

2022-02-04 11:24 UTC, purvesh-d commented on Swift-Advance.playground/Contents.swift
> +
Extra empty line

2022-02-07 03:59 UTC, purvesh-d requested changes

2022-02-07 03:59 UTC, purvesh-d commented on Swift-Advance-Exercise.playground/Contents.swift
> +class Character1 {
Class name should be proper

2022-02-07 03:59 UTC, purvesh-d commented on Swift-Advance-Exercise.playground/Contents.swift
> +    }else if item > 10 {
proper spacing

2022-03-04 03:58 UTC, Purvesh-Dodiya requested changes

2022-03-04 03:58 UTC, Purvesh-Dodiya commented on Demo app/Demo app/SecondViewController.swift
> +    var delegate : TextDelegate?
need mark for variable

2022-03-04 03:58 UTC, Purvesh-Dodiya commented on Demo app/Demo app/SecondViewController.swift
> +    override func viewDidLoad() {
Need mark

2022-03-04 03:58 UTC, Purvesh-Dodiya commented on Demo app/Demo app/SecondViewController.swift
> +    //MARK: - Outlet Action
mark should be outside the extension

2022-03-04 03:58 UTC, Purvesh-Dodiya commented on Demo app/Demo app/ViewController.swift
>      override func viewDidLoad() {
same

2022-03-04 03:58 UTC, Purvesh-Dodiya commented on Demo app/Demo app/ViewController.swift
> +// MARK: - New Part
give meaning full name to mark

2022-03-04 03:58 UTC, Purvesh-Dodiya commented on Demo app/Demo app/ViewController.swift
> +      if let controller = storyboard?.instantiateViewController(withIdentifier: "secondViewController") as? SecondViewController {
move identifier to constant file

2022-03-04 03:58 UTC, Purvesh-Dodiya commented on Swift-Advance.playground/Contents.swift
> +
pending

2022-03-04 05:22 UTC, jay-a-shah commented on Demo app/Demo app/SecondViewController.swift
> +    var delegate : TextDelegate?
Changes Done

2022-03-09 05:45 UTC, merged