UI Components Practical
jay-a-shah/ios_Demo-app1 pull request #5
Opened 2022-03-31 11:11 UTC by jay-a-shah

2022-04-14 09:03 UTC, purvesh-d requested changes

2022-04-14 09:03 UTC, purvesh-d commented on Demo app/Demo app/LoginAndSignUpScreen/WebViewController.swift
> +//MARK: - Outlet
Why you have did this changes?

2022-04-14 09:03 UTC, purvesh-d commented on Demo app/Demo app/LoginAndSignUpScreen/WebViewController.swift
> -        guard let url = URL(string: Constants.googleUrl) else {
Why you have did this changes?

2022-04-14 09:03 UTC, purvesh-d commented on Demo app/Demo app/LoginAndSignUpScreen/WebViewController.swift
> +//        searchBar.text = ""
commented code

2022-04-15 13:01 UTC, purvesh-d approved these changes

2022-04-15 13:01 UTC, purvesh-d commented on Demo app/Demo app/DatePickerView.swift
> +        let toolBar = UIToolbar(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: 44))
move height to constant file

2022-04-15 13:01 UTC, purvesh-d commented on Demo app/Demo app/LoginPage.swift
> +    @IBOutlet weak var passwordTextField: UITextField!
MARK indentation is not proper

2022-04-15 13:01 UTC, purvesh-d commented on Demo app/Demo app/LoginPage.swift
> +        // Do any additional setup after loading the view.
remove unnecessary comments

2022-04-15 13:01 UTC, purvesh-d commented on Demo app/Demo app/LoginPage.swift
> +}
code formating is not proper

2022-04-15 13:01 UTC, purvesh-d commented on Demo app/Demo app/LoginPage.swift
> +            //emailTextField.resignFirstResponder()
why commented code?

2022-04-15 13:01 UTC, purvesh-d commented on Demo app/Demo app/TabBarController/HomeViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for:indexPath)
move identifier in constant file

2022-04-15 13:01 UTC, purvesh-d commented on Demo app/Demo app/TabBarController/HomeViewController.swift
> +        if let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "cell", for: indexPath) as? UICollectionViewCell {
move cell in constant file

2022-04-15 13:01 UTC, purvesh-d commented on Demo app/Demo app/TabBarController/MapViewController.swift
> +        case Constants.ONE: redirectToLocation(row: row, latitude: Constants.gandinagarLatitude, longitude: Constants.gandinagarLongitude)
code formatting required

2022-04-18 17:01 UTC, purvesh-d requested changes

2022-04-18 17:01 UTC, purvesh-d commented on Demo app/Demo app/DatePickerView.swift
> +        let toolBar = UIToolbar(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: 44))
pending

2022-04-18 17:01 UTC, purvesh-d commented on Demo app/Demo app/DatePickerView.swift
> +    @objc func onClickCancelBtn(){
make separate extension for objc func

2022-04-18 17:01 UTC, purvesh-d commented on Demo app/Demo app/LoginPage.swift
> +    @IBOutlet weak var passwordTextField: UITextField!
pending

2022-04-19 04:27 UTC, jay-a-shah commented on Demo app/Demo app/DatePickerView.swift
> +        let toolBar = UIToolbar(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: 44))
Done

2022-04-19 05:27 UTC, purvesh-d requested changes

2022-04-19 05:27 UTC, purvesh-d commented on Demo app/Demo app/ViewController.swift
> +            }
code formatting

2022-04-19 08:17 UTC, purvesh-d requested changes

2022-04-19 08:17 UTC, purvesh-d commented on Demo app/Demo app/TabBarController/ImageViewController.swift
> +        btnAddPhoto.layer.shadowOffset = CGSize(width: 200, height: 200)
constant width height

2022-04-20 05:55 UTC, purvesh-d requested changes

2022-04-20 05:55 UTC, purvesh-d commented on Demo app/Demo app/TabBarController/HomeViewController.swift
> +        }else{
code formatting required

2022-04-20 05:55 UTC, purvesh-d commented on Demo app/Demo app/TabBarController/HomeViewController.swift
> +extension HomeViewController: UICollectionViewDelegate {
remove this block if not required

2022-04-20 07:05 UTC, purvesh-d approved these changes

2022-04-20 07:05 UTC, merged